"""An attemt pt at fixing my models to be able to make independent and shared blogs

Revision ID: 14f999e08315
Revises: f79579c92d1d
Create Date: 2024-04-22 00:12:45.672928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14f999e08315'
down_revision = 'f79579c92d1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_blogs_owner_id_users'), 'users', ['owner_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_blogs_owner_id_users'), type_='foreignkey')
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###
