"""Added nullable=False for shared blog owners

Revision ID: 26df0e7957d6
Revises: c97066a245a1
Create Date: 2024-04-20 14:10:07.709931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26df0e7957d6'
down_revision = 'c97066a245a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_blog', schema=None) as batch_op:
        batch_op.alter_column('primary_owner',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('co_owner',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_blog', schema=None) as batch_op:
        batch_op.alter_column('co_owner',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('primary_owner',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
