"""Removed has_blog

Revision ID: 7ac616f64dff
Revises: 9a43be3584db
Create Date: 2024-04-17 13:14:48.694541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ac616f64dff'
down_revision = '9a43be3584db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('has_blog')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_blog', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
