"""Added date_joined, date_created(x2), and date_added to User, Blog, Post, and Favorite respectively.

Revision ID: 9a43be3584db
Revises: f4d7edd2bcb4
Create Date: 2024-04-16 11:11:11.775504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a43be3584db'
down_revision = 'f4d7edd2bcb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', sa.DateTime(), nullable=True))

    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_added', sa.DateTime(), nullable=True))

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', sa.DateTime(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_joined', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('date_joined')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('date_created')

    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_column('date_added')

    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.drop_column('date_created')

    # ### end Alembic commands ###
