"""Changed favorites to a many-to-many table

Revision ID: d4124cfc7a83
Revises: 84fe555bcd07
Create Date: 2024-04-19 22:28:00.673542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4124cfc7a83'
down_revision = '84fe555bcd07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blog_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_favorites_blog_id_blogs'), 'blogs', ['blog_id'], ['id'])
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_added', sa.DATETIME(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_favorites_blog_id_blogs'), type_='foreignkey')
        batch_op.drop_column('date_favorited')
        batch_op.drop_column('blog_id')

    # ### end Alembic commands ###
